project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - Overview.qmd
    - methods.qmd
    - Behaviour.qmd
    - Results.qmd
    - metrics_stats.qmd
    - rotorua.qmd
    - Reproducibility.qmd
    - Reference_List.qmd

website:
  title: "Meterological Lake Comparison"
  navbar:
    type: tabs
    left:
      - text: "Home"
        href: index.qmd
      - text: "Overview"
        href: overview.qmd
      - text: "Methods"
        href: methods.qmd
      - text: "Seasonal and event behaviour"
        href: behaviour_results.qmd
      - text: "Time Series"
        href: timeseries_results.qmd
      - text: "Metrics & stats"
        href: metrics_stats_results.qmd
      - text: "Rotorua demo"
        href: rotorua.qmd
      - text: "Reproducibility"
        href: reproducibility.qmd
      - text: "References"
        href: reference_list.qmd

metadata-files:
  - params.yml

bibliography: reference.bib

format:
  html:
    theme: lux
    css: custom.css
    toc: true
    toc-title: "Table of Content"
    toc-location: left
    page-layout: full
    code-fold: true
    df-print: paged

execute:
  echo: true
  warning: false
  message: false
