project:
  type: website
  output-dir: docs

website:
  title: "Meterological Lake Comparison"
  navbar:
    type: tabs
    left:
      - text: "Home"
        href: index.qmd
      - text: "Overview"
        href: Overview.qmd
      - text: "Rotorua demo"
        href: rotorua.qmd
      - text: "Methods"
        href: methods.qmd
      - text: "Behaviour"
        href: Behaviour.qmd
      - text: "Results"
        href: Results.qmd
      - text: "Reproducibility"
        href: Reproducibility.qmd

metadata-files:
  - params.yml

format:
  html:
    theme: lux
    css: custom.css
    toc: true
    toc-title: "Table of Content"
    toc-location: left
    page-layout: full
    code-fold: true
    df-print: paged

execute:
  echo: true
  warning: false
  message: false
